wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1724510252
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 86
      - 100
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 86
      - 100
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.17.3
      6: 4.40.2
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
